// Code generated by togo. DO NOT EDIT.
//
// Installed plugins are blank-imported here so their init() registers them with
// the kernel for auto-discovery. `togo install owner/repo` regenerates this file.
package plugins

import (
	// Auth: users, sessions/JWT, CSRF and the admin API at /api/auth/admin/*.
	_ "github.com/togo-framework/auth"
	// Dynamic config store — powers the settings tier of provider selection.
	_ "github.com/togo-framework/settings"
	// Data capability (uniform Query; default pg backend → pg_analytics + pg_search).
	_ "github.com/togo-framework/data"
)
