// Code generated by togo. DO NOT EDIT.
//
// Installed plugins are blank-imported here so their init() registers them with
// the kernel for auto-discovery. `togo install owner/repo` regenerates this file.
package plugins
