// Code generated by togo. DO NOT EDIT.
//
// Installed plugins are blank-imported here so their init() registers them with
// the kernel for auto-discovery. `togo install owner/repo` regenerates this file.
package plugins

import (
	// Dynamic config store — powers the settings tier of provider selection.
	_ "github.com/togo-framework/settings"
	// Data capability (uniform Query; default pg backend → pg_analytics + pg_search).
	_ "github.com/togo-framework/data"
	// Autopilot — the in-app Issues → Agent → Code → Deploy loop (provider-aware:
	// impl=claude / exec=local by default; install coder/omnigent to swap).
	_ "github.com/togo-framework/autopilot"
)
