// Code generated by togo. DO NOT EDIT.
package rest

import "github.com/danielgtaylor/huma/v2"

// RegisterRoutes mounts every generated resource's REST routes. This empty
// starter is overwritten the first time you run `togo make:resource`.
func RegisterRoutes(api huma.API) {
}
